---
- name: apt_update
  apt: update_cache=yes

- name: restart_sshd
  service:
    name: "{{ openssh_service }}"
    state: restarted

- name: update_tmux_plugin_perms
  file:
    path: /home/example_user/.tmux/plugins
    owner: example_user
    group: example_user
    recurse: true

- name: update_vim_bundle_perms
  file:
    path: /home/example_user/.vim/bundle
    owner: example_user
    group: example_user
    recurse: true
