- name: software | mattermost | install package
  tags: packages,flatpak,mattermost,workstation-packages
  become_user: example_user
  flatpak:
    name: com.mattermost.Desktop
    method: user
    state: present
  when: mattermost is defined and mattermost == true

- name: software | mattermost | enable autostart
  tags: packages,flatpak,mattermost,workstation-packages
  file:
    src: /home/example_user/.local/share/flatpak/exports/share/applications/com.mattermost.Desktop.desktop
    dest: /home/example_user/.config/autostart/com.mattermost.Desktop.desktop
    owner: example_user
    group: example_user
    state: link
  when: mattermost is defined and mattermost == true
