---
- name: Copy notify-send-all file to /usr/local/bin
  copy:
    src: ./files/notify-send-all
    dest: /usr/local/bin/
    mode: '0755'
  become: true
- name: Popup Notification
  command: notify-send-all -t 10 "Ansible" "Ansible was just run on this computer from github"
  register: result

