---
# n8htpc configuration

# User configuration
user_configs:
  - system_user: root
    config_profile: root
  - system_user: nsheaps
    config_profile: nsheaps

# Ansible pull configuration
ansible_cron_minute: "*/30"

# Healthchecks.io monitoring
healthchecks_io_uuid: "{{ vault_healthchecks_io_uuid_n8htpc | default('') }}"
healthchecks_io_enabled: true