- name: ansible setup | ensure ansible is installed
  tags: ansible,ansible-setup
  package:
    name: ansible
    state: present

- name: ansible setup | install required packages for ansible modules
  tags: ansible,ansible-setup,packages
  package:
    name:
      - "{{ dconf_package }}"
      - "{{ python_psutil_package }}"

# Note: For Arch, the requirement is met by a dependency of systemd, only necessary on Debian-based
- name: ansible setup | install acl package
  tags: ansible,ansible-setup,packages
  package:
    name: acl
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

- name: ansible setup | remove default ansible directory (/etc/ansible) from host
  tags: ansible,ansible-setup
  file:
    path: /etc/ansible
    state: absent
